[workspace]
members = ["programs/ginva"]
exclude = ["programs/ginva_flash_bot", "programs/ginva-pinocchio", "programs/ginva-pinocchio/*"]
resolver = "2"

[workspace.dependencies]
anchor-lang = "0.29.0"
anchor-spl = "0.29.0"
blake3 = "=1.5.5"
constant_time_eq = "=0.3.1"
base64ct = "=1.6.0"
borsh = "1.5.5"
borsh-derive = "1.0.4"
toml_edit = "0.22.0"
toml_parser = "0.10.0"

# Force Cargo.lock version 3 compatibility
[workspace.metadata]
cargo = { lockfile = { version = 3 } }


[profile.dev]
overflow-checks = true

[profile.release]
overflow-checks = true
lto = "fat"
codegen-units = 1
[profile.release.build-override]
opt-level = 3
incremental = false
codegen-units = 1
