[package]
name = "ginva-pinocchio"
version = "2.0.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[features]
default = ["std"]
std = []

[dependencies]
pinocchio = "0.9"
pinocchio-system = "0.4"
pinocchio-token = "0.4"
solana-program-error = "2.0"
blake3 = "1.5"
constant_time_eq = "0.2"
base64ct = "1.6"
hashbrown = "0.14"

[dependencies.cpufeatures]
version = "=0.2.17"

[lints.rust]
unexpected_cfgs = "allow"

[profile.release]
overflow-checks = true  # panic on overflow in release (safe math)
lto = false
codegen-units = 16
debug = 0
strip = true

[package.metadata.sbpf.build]
linker = "bfg-links"