[package]
name = "ginva"
version = "2.0.0"
edition = "2021"

[features]
default = ["anchor-lang/init-if-needed"]
devnet = ["anchor-lang/init-if-needed"]
no-entrypoint = []
cpi = ["no-entrypoint"]
custom-heap = []
custom-panic = []
no-idl = []
anchor-debug = []
no-log-ix-name = []
local-test = []

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
anchor-lang = { version = "0.24.2", features = ["init-if-needed"] }
anchor-spl = "0.24.2"
solana-program = "1.9.29"
pyth-solana-receiver-sdk-legacy = "0.3.3"
blake3 = "=1.5.5"
constant_time_eq = "=0.3.1"
base64ct = "=1.6.0"
hashbrown = "=0.14.0"
